apiVersion: v1
kind: Service
metadata:
  name: addon-operator-webhook
  namespace: openshift-addon-operator
  labels:
    app.kubernetes.io/name: addon-operator
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: addon-operator-webhook-tls
    package-operator.run/phase: deploy
    package-operator.run/collision-protection: IfNoController
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: https
    port: 443
    targetPort: 8080
  selector:
    app.kubernetes.io/name: addon-operator
