apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addon-operator-prom-token-role
  annotations:
    package-operator.run/phase: rbac
    package-operator.run/collision-protection: IfNoController
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
