apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: addon-operator-prom-token
    package-operator.run/phase: rbac
    package-operator.run/collision-protection: IfNoController
  labels:
    name: addon-operator
  name: addon-operator-prom-token
  namespace: openshift-addon-operator
type: kubernetes.io/service-account-token
